env: dev
title: Emily Romick & Jason Kühn Get Hitched, Have Party
email: spaceyraygun@gmail.com
description: Emily Romick and Jason Kühn throw a wedding party at Philadelphia's Mask & Wig Club on April 29, 2017
url: http://localhost:4000
github_username:  jklmnop
markdown: kramdown
exclude:
 - package.json
 - node_modules
 - gulpfile.js
 - README.md
 - sass