title: Romickühn
slogan: Gettin' hitched
email: spaceyraygun@gmail.com
description: Romickühn
baseurl: "https://jklmnop.github.io/romickuhn"
url: "https://jklmnop.github.io/romickuhn"
logo: ""
github_username:  jklmnop
markdown: kramdown
exclude:
 - package.json
 - node_modules
 - gulpfile.js
 - README.md
 - sass