env: prod
title: Romickühn
slogan: Gettin' hitched
email: spaceyraygun@gmail.com
description: Romickühn
url: http://romickuhn.com
github_username:  jklmnop
markdown: kramdown
exclude:
 - package.json
 - node_modules
 - gulpfile.js
 - README.md
 - sass