title: Romickühn
slogan: Gettin' hitched
email: spaceyraygun@gmail.com
description: Romickühn
baseurl: "http://romickuhn.com"
url: "http://romickuhn.com"
logo: ""
github_username:  jklmnop
markdown: kramdown
exclude:
 - package.json
 - node_modules
 - gulpfile.js
 - README.md
 - sass